import { useState } from "react";
import { Bot, BookOpenCheck, Send, Sparkles, User } from "lucide-react";
import { api } from "../lib/api";

export function AITutor(){
 const [message,setMessage]=useState(""),[messages,setMessages]=useState<{role:string,text:string}[]>([{role:"ai",text:"Hi! I’m your NCERT revision tutor. Ask me to explain a concept, create a quick quiz, or help you understand a mistake."}]),[loading,setLoading]=useState(false);
 async function send(text=message){if(!text.trim())return;setMessages(m=>[...m,{role:"user",text}]);setMessage("");setLoading(true);try{const r=await api.post("/ai/chat",{message:text,context:[{title:"Approved NCERT learning content",chapter:"Class 11 revision",page:1,chunkId:"demo-1"}]});setMessages(m=>[...m,{role:"ai",text:r.data.data.answer}])}catch{setMessages(m=>[...m,{role:"ai",text:"Demo mode: connect an AI provider in the API .env to get grounded model responses."}])}finally{setLoading(false)}}
 return <div className="mx-auto max-w-5xl space-y-6"><div><div className="inline-flex items-center gap-2 rounded-full bg-violet-400/10 px-3 py-1 text-[10px] font-black text-violet-300"><Sparkles size={12}/> GROUNDED AI</div><h1 className="mt-3 text-3xl font-black">Your personal study tutor.</h1><p className="mt-2 text-sm text-slate-500">Ask questions naturally. The production RAG layer is designed to answer from approved source material.</p></div>
 <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><section className="glass flex min-h-[580px] flex-col rounded-[30px]"><div className="flex items-center gap-3 border-b border-white/10 p-5"><div className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-cyan-400"><Bot size={19}/></div><div><div className="font-black">NCERT Tutor</div><div className="text-[10px] text-emerald-300">● Ready to help</div></div></div><div className="flex-1 space-y-4 overflow-auto p-5">{messages.map((m,i)=><div key={i} className={`flex gap-3 ${m.role==="user"?"justify-end":""}`}><div className={`max-w-[85%] rounded-2xl p-4 text-sm leading-6 ${m.role==="user"?"bg-violet-500/15 border border-violet-400/10":"bg-white/[.04] border border-white/5"}`}>{m.text}</div></div>)}{loading&&<div className="text-xs text-slate-600">Thinking from your approved learning context…</div>}</div><div className="border-t border-white/10 p-4"><div className="flex gap-2 rounded-2xl border border-white/10 bg-white/[.03] p-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask: explain Newton's second law simply..." className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-slate-600"/><button onClick={()=>send()} className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-slate-900"><Send size={16}/></button></div></div></section>
 <aside className="space-y-3"><div className="glass rounded-[24px] p-5"><div className="flex items-center gap-2 font-black"><BookOpenCheck size={17} className="text-cyan-300"/> Try asking</div><div className="mt-4 space-y-2">{["Explain friction with an example","Quiz me on Laws of Motion","Why does acceleration change?","Make 5 revision flashcards"].map(x=><button key={x} onClick={()=>send(x)} className="w-full rounded-xl bg-white/[.035] p-3 text-left text-xs font-semibold text-slate-400 hover:text-white">{x}</button>)}</div></div></aside></div></div>
}
