import { ArrowUpRight, BrainCircuit, CheckCircle2, Clock3, Target, TrendingUp } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
const data=[{d:"Mon",a:64},{d:"Tue",a:71},{d:"Wed",a:69},{d:"Thu",a:76},{d:"Fri",a:74},{d:"Sat",a:82},{d:"Sun",a:86}];
const stats = [
  { v: "78%", l: "Average accuracy", Icon: TrendingUp },
  { v: "423", l: "Questions solved", Icon: CheckCircle2 },
  { v: "12.4h", l: "Study time", Icon: Clock3 },
  { v: "16", l: "Concepts mastered", Icon: Target }
];

export function Analytics(){return <div className="space-y-7"><div><div className="text-xs font-bold text-cyan-300">YOUR PROGRESS</div><h1 className="mt-2 text-3xl font-black">Analytics that help you improve.</h1><p className="mt-2 text-sm text-slate-500">Understand where you are strong and where your next revision session should go.</p></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(({v,l,Icon})=><div className="glass rounded-3xl p-5" key={l}><Icon size={19} className="text-violet-300"/><div className="mt-4 text-2xl font-black">{v}</div><div className="mt-1 text-xs text-slate-500">{l}</div></div>)}</div><section className="glass rounded-[30px] p-5 sm:p-7"><div className="flex justify-between"><div><h2 className="font-black">Accuracy trend</h2><p className="mt-1 text-xs text-slate-500">Last seven days</p></div><span className="inline-flex items-center gap-1 rounded-xl bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">+12% <ArrowUpRight size={14}/></span></div><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#22d3ee" stopOpacity=".3"/><stop offset="1" stopColor="#22d3ee" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fill:"#64748b",fontSize:11}}/><YAxis domain={[40,100]} axisLine={false} tickLine={false} tick={{fill:"#64748b",fontSize:11}}/><Tooltip contentStyle={{background:"#0f1b2d",border:"1px solid rgba(255,255,255,.1)",borderRadius:14}}/><Area dataKey="a" stroke="#22d3ee" fill="url(#a)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><div className="grid gap-4 md:grid-cols-3">{["Friction","Thermodynamics","Integration"].map((x,i)=><div className="glass rounded-3xl p-5" key={x}><div className="text-[10px] font-black uppercase text-slate-600">Needs focus</div><h3 className="mt-2 font-black">{x}</h3><div className="mt-3 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-orange-400 to-red-400" style={{width:`${48+i*6}%`}}/></div><div className="mt-2 text-xs text-slate-500">Build mastery with a focused session.</div></div>)}</div></div>}
